players = {
    "Lionel Messi": {"Country": "Argentina", "Club": "Inter Miami", "Age": 39, "Position": "Forward"},
    "Cristiano Ronaldo": {"Country": "Portugal", "Club": "Al Nassr", "Age": 41, "Position": "Forward"},
    "Kylian Mbappé": {"Country": "France", "Club": "Real Madrid", "Age": 27, "Position": "Forward"},
    "Erling Haaland": {"Country": "Norway", "Club": "Manchester City", "Age": 25, "Position": "Forward"},
    "Kevin De Bruyne": {"Country": "Belgium", "Club": "Manchester City", "Age": 35, "Position": "Midfielder"},
    "Jude Bellingham": {"Country": "England", "Club": "Real Madrid", "Age": 23, "Position": "Midfielder"},
    "Vinícius Júnior": {"Country": "Brazil", "Club": "Real Madrid", "Age": 25, "Position": "Forward"},
    "Harry Kane": {"Country": "England", "Club": "Bayern Munich", "Age": 32, "Position": "Forward"},
    "Mohamed Salah": {"Country": "Egypt", "Club": "Liverpool", "Age": 34, "Position": "Forward"},
    "Robert Lewandowski": {"Country": "Poland", "Club": "Barcelona", "Age": 37, "Position": "Forward"},
    "Luka Modrić": {"Country": "Croatia", "Club": "Real Madrid", "Age": 40, "Position": "Midfielder"},
    "Antoine Griezmann": {"Country": "France", "Club": "Atlético Madrid", "Age": 35, "Position": "Forward"},
    "Virgil van Dijk": {"Country": "Netherlands", "Club": "Liverpool", "Age": 34, "Position": "Defender"},
    "Alisson Becker": {"Country": "Brazil", "Club": "Liverpool", "Age": 33, "Position": "Goalkeeper"},
    "Thibaut Courtois": {"Country": "Belgium", "Club": "Real Madrid", "Age": 34, "Position": "Goalkeeper"},
    "Rodri": {"Country": "Spain", "Club": "Manchester City", "Age": 30, "Position": "Midfielder"},
    "Bernardo Silva": {"Country": "Portugal", "Club": "Manchester City", "Age": 31, "Position": "Midfielder"},
    "Bruno Fernandes": {"Country": "Portugal", "Club": "Manchester United", "Age": 31, "Position": "Midfielder"},
    "Bukayo Saka": {"Country": "England", "Club": "Arsenal", "Age": 24, "Position": "Forward"},
    "Martin Ødegaard": {"Country": "Norway", "Club": "Arsenal", "Age": 27, "Position": "Midfielder"},
    "Declan Rice": {"Country": "England", "Club": "Arsenal", "Age": 27, "Position": "Midfielder"},
    "Jamal Musiala": {"Country": "Germany", "Club": "Bayern Munich", "Age": 23, "Position": "Midfielder"},
    "Florian Wirtz": {"Country": "Germany", "Club": "Bayer Leverkusen", "Age": 23, "Position": "Midfielder"},
    "Heung-min Son": {"Country": "South Korea", "Club": "Tottenham Hotspur", "Age": 33, "Position": "Forward"},
    "Lautaro Martínez": {"Country": "Argentina", "Club": "Inter Milan", "Age": 28, "Position": "Forward"},
    "Rafael Leão": {"Country": "Portugal", "Club": "AC Milan", "Age": 27, "Position": "Forward"},
    "Victor Osimhen": {"Country": "Nigeria", "Club": "Galatasaray", "Age": 27, "Position": "Forward"},
    "Khvicha Kvaratskhelia": {"Country": "Georgia", "Club": "Napoli", "Age": 25, "Position": "Forward"},
    "Neymar Jr": {"Country": "Brazil", "Club": "Al Hilal", "Age": 34, "Position": "Forward"},
    "Karim Benzema": {"Country": "France", "Club": "Al Ittihad", "Age": 38, "Position": "Forward"},
    "Pedri": {"Country": "Spain", "Club": "Barcelona", "Age": 23, "Position": "Midfielder"},
    "Gavi": {"Country": "Spain", "Club": "Barcelona", "Age": 21, "Position": "Midfielder"},
    "Lamine Yamal": {"Country": "Spain", "Club": "Barcelona", "Age": 18, "Position": "Forward"},
    "Eduardo Camavinga": {"Country": "France", "Club": "Real Madrid", "Age": 23, "Position": "Midfielder"},
    "Aurélien Tchouaméni": {"Country": "France", "Club": "Real Madrid", "Age": 26, "Position": "Midfielder"},
    "Federico Valverde": {"Country": "Uruguay", "Club": "Real Madrid", "Age": 27, "Position": "Midfielder"},
    "Antonio Rüdiger": {"Country": "Germany", "Club": "Real Madrid", "Age": 33, "Position": "Defender"},
    "Ruben Dias": {"Country": "Portugal", "Club": "Manchester City", "Age": 29, "Position": "Defender"},
    "John Stones": {"Country": "England", "Club": "Manchester City", "Age": 32, "Position": "Defender"},
    "Kyle Walker": {"Country": "England", "Club": "Manchester City", "Age": 36, "Position": "Defender"},
    "Ederson": {"Country": "Brazil", "Club": "Manchester City", "Age": 32, "Position": "Goalkeeper"},
    "William Saliba": {"Country": "France", "Club": "Arsenal", "Age": 25, "Position": "Defender"},
    "Gabriel Magalhães": {"Country": "Brazil", "Club": "Arsenal", "Age": 28, "Position": "Defender"},
    "Achraf Hakimi": {"Country": "Morocco", "Club": "Paris Saint-Germain", "Age": 27, "Position": "Defender"},
    "Ousmane Dembélé": {"Country": "France", "Club": "Paris Saint-Germain", "Age": 29, "Position": "Forward"},
    "Warren Zaïre-Emery": {"Country": "France", "Club": "Paris Saint-Germain", "Age": 20, "Position": "Midfielder"},
    "Marquinhos": {"Country": "Brazil", "Club": "Paris Saint-Germain", "Age": 32, "Position": "Defender"},
    "Gianluigi Donnarumma": {"Country": "Italy", "Club": "Paris Saint-Germain", "Age": 27, "Position": "Goalkeeper"},
    "Leroy Sané": {"Country": "Germany", "Club": "Bayern Munich", "Age": 30, "Position": "Forward"},
    "Joshua Kimmich": {"Country": "Germany", "Club": "Bayern Munich", "Age": 31, "Position": "Midfielder"},
    "Alphonso Davies": {"Country": "Canada", "Club": "Bayern Munich", "Age": 25, "Position": "Defender"},
    "Manuel Neuer": {"Country": "Germany", "Club": "Bayern Munich", "Age": 40, "Position": "Goalkeeper"},
    "Theo Hernandez": {"Country": "France", "Club": "AC Milan", "Age": 28, "Position": "Defender"},
    "Mike Maignan": {"Country": "France", "Club": "AC Milan", "Age": 30, "Position": "Goalkeeper"},
    "Nicolò Barella": {"Country": "Italy", "Club": "Inter Milan", "Age": 29, "Position": "Midfielder"},
    "Alessandro Bastoni": {"Country": "Italy", "Club": "Inter Milan", "Age": 27, "Position": "Defender"},
    "Hakan Çalhanoğlu": {"Country": "Turkey", "Club": "Inter Milan", "Age": 32, "Position": "Midfielder"},
    "Yann Sommer": {"Country": "Switzerland", "Club": "Inter Milan", "Age": 37, "Position": "Goalkeeper"},
    "Dušan Vlahović": {"Country": "Serbia", "Club": "Juventus", "Age": 26, "Position": "Forward"},
    "Federico Chiesa": {"Country": "Italy", "Club": "Liverpool", "Age": 28, "Position": "Forward"},
    "Gleison Bremer": {"Country": "Brazil", "Club": "Juventus", "Age": 29, "Position": "Defender"},
    "Luis Díaz": {"Country": "Colombia", "Club": "Liverpool", "Age": 29, "Position": "Forward"},
    "Alexis Mac Allister": {"Country": "Argentina", "Club": "Liverpool", "Age": 27, "Position": "Midfielder"},
    "Dominik Szoboszlai": {"Country": "Hungary", "Club": "Liverpool", "Age": 25, "Position": "Midfielder"},
    "Darwin Núñez": {"Country": "Uruguay", "Club": "Liverpool", "Age": 27, "Position": "Forward"},
    "Marcus Rashford": {"Country": "England", "Club": "Manchester United", "Age": 28, "Position": "Forward"},
    "Alejandro Garnacho": {"Country": "Argentina", "Club": "Manchester United", "Age": 21, "Position": "Forward"},
    "Kobbie Mainoo": {"Country": "England", "Club": "Manchester United", "Age": 21, "Position": "Midfielder"},
    "Matthijs de Ligt": {"Country": "Netherlands", "Club": "Manchester United", "Age": 26, "Position": "Defender"},
    "André Onana": {"Country": "Cameroon", "Club": "Manchester United", "Age": 30, "Position": "Goalkeeper"},
    "Cole Palmer": {"Country": "England", "Club": "Chelsea", "Age": 24, "Position": "Midfielder"},
    "Enzo Fernández": {"Country": "Argentina", "Club": "Chelsea", "Age": 25, "Position": "Midfielder"},
    "Moises Caicedo": {"Country": "Ecuador", "Club": "Chelsea", "Age": 24, "Position": "Midfielder"},
    "Reece James": {"Country": "England", "Club": "Chelsea", "Age": 26, "Position": "Defender"},
    "Christopher Nkunku": {"Country": "France", "Club": "Chelsea", "Age": 28, "Position": "Forward"},
    "James Maddison": {"Country": "England", "Club": "Tottenham Hotspur", "Age": 29, "Position": "Midfielder"},
    "Cristian Romero": {"Country": "Argentina", "Club": "Tottenham Hotspur", "Age": 28, "Position": "Defender"},
    "Guglielmo Vicario": {"Country": "Italy", "Club": "Tottenham Hotspur", "Age": 29, "Position": "Goalkeeper"},
    "Alexander Isak": {"Country": "Sweden", "Club": "Newcastle United", "Age": 26, "Position": "Forward"},
    "Bruno Guimarães": {"Country": "Brazil", "Club": "Newcastle United", "Age": 28, "Position": "Midfielder"},
    "Anthony Gordon": {"Country": "England", "Club": "Newcastle United", "Age": 25, "Position": "Forward"},
    "Kieran Trippier": {"Country": "England", "Club": "Newcastle United", "Age": 35, "Position": "Defender"},
    "Ollie Watkins": {"Country": "England", "Club": "Aston Villa", "Age": 30, "Position": "Forward"},
    "Emi Martínez": {"Country": "Argentina", "Club": "Aston Villa", "Age": 33, "Position": "Goalkeeper"},
    "Douglas Luiz": {"Country": "Brazil", "Club": "Juventus", "Age": 28, "Position": "Midfielder"},
    "Lucas Paquetá": {"Country": "Brazil", "Club": "West Ham United", "Age": 28, "Position": "Midfielder"},
    "Jarrod Bowen": {"Country": "England", "Club": "West Ham United", "Age": 29, "Position": "Forward"},
    "Mohammed Kudus": {"Country": "Ghana", "Club": "West Ham United", "Age": 25, "Position": "Midfielder"},
    "Amadou Onana": {"Country": "Belgium", "Club": "Aston Villa", "Age": 24, "Position": "Midfielder"},
    "João Palhinha": {"Country": "Portugal", "Club": "Bayern Munich", "Age": 30, "Position": "Midfielder"},
    "Granit Xhaka": {"Country": "Switzerland", "Club": "Bayer Leverkusen", "Age": 33, "Position": "Midfielder"},
    "Jeremie Frimpong": {"Country": "Netherlands", "Club": "Bayer Leverkusen", "Age": 25, "Position": "Defender"},
    "Alejandro Grimaldo": {"Country": "Spain", "Club": "Bayer Leverkusen", "Age": 30, "Position": "Defender"},
    "Victor Boniface": {"Country": "Nigeria", "Club": "Bayer Leverkusen", "Age": 25, "Position": "Forward"},
    "Jonathan Tah": {"Country": "Germany", "Club": "Bayer Leverkusen", "Age": 30, "Position": "Defender"},
    "Lukas Hradecky": {"Country": "Finland", "Club": "Bayer Leverkusen", "Age": 36, "Position": "Goalkeeper"},
    "Gregor Kobel": {"Country": "Switzerland", "Club": "Borussia Dortmund", "Age": 28, "Position": "Goalkeeper"},
    "Julian Brandt": {"Country": "Germany", "Club": "Borussia Dortmund", "Age": 30, "Position": "Midfielder"},
    "Nico Schlotterbeck": {"Country": "Germany", "Club": "Borussia Dortmund", "Age": 26, "Position": "Defender"},
    "Marcel Sabitzer": {"Country": "Austria", "Club": "Borussia Dortmund", "Age": 32, "Position": "Midfielder"},
    "Serge Gnabry": {"Country": "Germany", "Club": "Bayern Munich", "Age": 30, "Position": "Forward"},
    "Kingsley Coman": {"Country": "France", "Club": "Bayern Munich", "Age": 30, "Position": "Forward"},
    "Dayot Upamecano": {"Country": "France", "Club": "Bayern Munich", "Age": 27, "Position": "Defender"},
    "Kim Min-jae": {"Country": "South Korea", "Club": "Bayern Munich", "Age": 29, "Position": "Defender"},
    "Frenkie de Jong": {"Country": "Netherlands", "Club": "Barcelona", "Age": 29, "Position": "Midfielder"},
    "Ilkay Gündogan": {"Country": "Germany", "Club": "Manchester City", "Age": 35, "Position": "Midfielder"},
    "Raphinha": {"Country": "Brazil", "Club": "Barcelona", "Age": 29, "Position": "Forward"},
    "Ronald Araújo": {"Country": "Uruguay", "Club": "Barcelona", "Age": 27, "Position": "Defender"},
    "Jules Koundé": {"Country": "France", "Club": "Barcelona", "Age": 27, "Position": "Defender"},
    "Marc-André ter Stegen": {"Country": "Germany", "Club": "Barcelona", "Age": 34, "Position": "Goalkeeper"},
    "Jan Oblak": {"Country": "Slovenia", "Club": "Atlético Madrid", "Age": 33, "Position": "Goalkeeper"},
    "Rodrigo De Paul": {"Country": "Argentina", "Club": "Atlético Madrid", "Age": 32, "Position": "Midfielder"},
    "Marcos Llorente": {"Country": "Spain", "Club": "Atlético Madrid", "Age": 31, "Position": "Midfielder"},
    "Álvaro Morata": {"Country": "Spain", "Club": "AC Milan", "Age": 33, "Position": "Forward"},
    "Nico Williams": {"Country": "Spain", "Club": "Athletic Bilbao", "Age": 23, "Position": "Forward"},
    "Dani Olmo": {"Country": "Spain", "Club": "Barcelona", "Age": 28, "Position": "Midfielder"},
    "Martin Zubimendi": {"Country": "Spain", "Club": "Real Sociedad", "Age": 27, "Position": "Midfielder"},
    "Mikel Merino": {"Country": "Spain", "Club": "Arsenal", "Age": 30, "Position": "Midfielder"},
    "Alex Remiro": {"Country": "Spain", "Club": "Real Sociedad", "Age": 31, "Position": "Goalkeeper"},
    "Unai Simón": {"Country": "Spain", "Club": "Athletic Bilbao", "Age": 29, "Position": "Goalkeeper"},
    "Arda Güler": {"Country": "Turkey", "Club": "Real Madrid", "Age": 21, "Position": "Midfielder"},
    "Brahim Díaz": {"Country": "Morocco", "Club": "Real Madrid", "Age": 26, "Position": "Midfielder"},
    "Ferland Mendy": {"Country": "France", "Club": "Real Madrid", "Age": 31, "Position": "Defender"},
    "Dani Carvajal": {"Country": "Spain", "Club": "Real Madrid", "Age": 34, "Position": "Defender"},
    "Éder Militão": {"Country": "Brazil", "Club": "Real Madrid", "Age": 28, "Position": "Defender"},
    "Lucas Vázquez": {"Country": "Spain", "Club": "Real Madrid", "Age": 34, "Position": "Defender"},
    "Joselu": {"Country": "Spain", "Club": "Al Gharafa", "Age": 36, "Position": "Forward"},
    "Riyad Mahrez": {"Country": "Algeria", "Club": "Al Ahli", "Age": 35, "Position": "Forward"},
    "Sadio Mané": {"Country": "Senegal", "Club": "Al Nassr", "Age": 34, "Position": "Forward"},
    "Aymeric Laporte": {"Country": "Spain", "Club": "Al Nassr", "Age": 32, "Position": "Defender"},
    "Marcelo Brozović": {"Country": "Croatia", "Club": "Al Nassr", "Age": 33, "Position": "Midfielder"},
    "Otávio": {"Country": "Portugal", "Club": "Al Nassr", "Age": 31, "Position": "Midfielder"},
    "Sergej Milinković-Savić": {"Country": "Serbia", "Club": "Al Hilal", "Age": 31, "Position": "Midfielder"},
    "Ruben Neves": {"Country": "Portugal", "Club": "Al Hilal", "Age": 29, "Position": "Midfielder"},
    "Aleksandar Mitrović": {"Country": "Serbia", "Club": "Al Hilal", "Age": 31, "Position": "Forward"},
    "Yassine Bounou": {"Country": "Morocco", "Club": "Al Hilal", "Age": 35, "Position": "Goalkeeper"},
    "Kalidou Koulibaly": {"Country": "Senegal", "Club": "Al Hilal", "Age": 35, "Position": "Defender"},
    "N'Golo Kanté": {"Country": "France", "Club": "Al Ittihad", "Age": 35, "Position": "Midfielder"},
    "Fabinho": {"Country": "Brazil", "Club": "Al Ittihad", "Age": 32, "Position": "Midfielder"},
    "Moussa Diaby": {"Country": "France", "Club": "Al Ittihad", "Age": 27, "Position": "Forward"},
    "Roberto Firmino": {"Country": "Brazil", "Club": "Al Ahli", "Age": 34, "Position": "Forward"},
    "Franck Kessié": {"Country": "Ivory Coast", "Club": "Al Ahli", "Age": 29, "Position": "Midfielder"},
    "Edouard Mendy": {"Country": "Senegal", "Club": "Al Ahli", "Age": 34, "Position": "Goalkeeper"},
    "Ivan Perišić": {"Country": "Croatia", "Club": "Hajduk Split", "Age": 37, "Position": "Forward"},
    "Marcelo": {"Country": "Brazil", "Club": "Fluminense", "Age": 38, "Position": "Defender"},
    "Luis Suárez": {"Country": "Uruguay", "Club": "Inter Miami", "Age": 39, "Position": "Forward"},
    "Sergio Busquets": {"Country": "Spain", "Club": "Inter Miami", "Age": 37, "Position": "Midfielder"},
    "Jordi Alba": {"Country": "Spain", "Club": "Inter Miami", "Age": 37, "Position": "Defender"},
    "Olivier Giroud": {"Country": "France", "Club": "LAFC", "Age": 39, "Position": "Forward"},
    "Emil Forsberg": {"Country": "Sweden", "Club": "New York Red Bulls", "Age": 34, "Position": "Midfielder"},
    "Lorenzo Insigne": {"Country": "Italy", "Club": "Toronto FC", "Age": 35, "Position": "Forward"},
    "Federico Bernardeschi": {"Country": "Italy", "Club": "Toronto FC", "Age": 32, "Position": "Forward"},
    "Xerdan Shaqiri": {"Country": "Switzerland", "Club": "Basel", "Age": 34, "Position": "Midfielder"},
    "Angel Di Maria": {"Country": "Argentina", "Club": "Benfica", "Age": 38, "Position": "Forward"},
    "Nicolas Otamendi": {"Country": "Argentina", "Club": "Benfica", "Age": 38, "Position": "Defender"},
    "Anatoliy Trubin": {"Country": "Ukraine", "Club": "Benfica", "Age": 24, "Position": "Goalkeeper"},
    "Viktor Gyökeres": {"Country": "Sweden", "Club": "Sporting CP", "Age": 28, "Position": "Forward"},
    "Pedro Gonçalves": {"Country": "Portugal", "Club": "Sporting CP", "Age": 28, "Position": "Midfielder"},
    "Gonçalo Inácio": {"Country": "Portugal", "Club": "Sporting CP", "Age": 24, "Position": "Defender"},
    "Diogo Costa": {"Country": "Portugal", "Club": "FC Porto", "Age": 26, "Position": "Goalkeeper"},
    "Alan Varela": {"Country": "Argentina", "Club": "FC Porto", "Age": 24, "Position": "Midfielder"},
    "Santiago Giménez": {"Country": "Mexico", "Club": "Feyenoord", "Age": 25, "Position": "Forward"},
    "Dávid Hancko": {"Country": "Slovakia", "Club": "Feyenoord", "Age": 28, "Position": "Defender"},
    "Lutsharel Geertruida": {"Country": "Netherlands", "Club": "RB Leipzig", "Age": 25, "Position": "Defender"},
    "Joey Veerman": {"Country": "Netherlands", "Club": "PSV Eindhoven", "Age": 27, "Position": "Midfielder"},
    "Johan Bakayoko": {"Country": "Belgium", "Club": "PSV Eindhoven", "Age": 23, "Position": "Forward"},
    "Luuk de Jong": {"Country": "Netherlands", "Club": "PSV Eindhoven", "Age": 35, "Position": "Forward"},
    "Brian Brobbey": {"Country": "Netherlands", "Club": "Ajax", "Age": 24, "Position": "Forward"},
    "Steven Bergwijn": {"Country": "Netherlands", "Club": "Al Ittihad", "Age": 28, "Position": "Forward"},
    "Jordan Henderson": {"Country": "England", "Club": "Ajax", "Age": 36, "Position": "Midfielder"},
    "Mauro Icardi": {"Country": "Argentina", "Club": "Galatasaray", "Age": 33, "Position": "Forward"},
    "Dries Mertens": {"Country": "Belgium", "Club": "Galatasaray", "Age": 39, "Position": "Forward"},
    "Lucas Torreira": {"Country": "Uruguay", "Club": "Galatasaray", "Age": 30, "Position": "Midfielder"},
    "Edin Džeko": {"Country": "Bosnia", "Club": "Fenerbahçe", "Age": 40, "Position": "Forward"},
    "Dušan Tadić": {"Country": "Serbia", "Club": "Fenerbahçe", "Age": 37, "Position": "Forward"},
    "Fred": {"Country": "Brazil", "Club": "Fenerbahçe", "Age": 33, "Position": "Midfielder"},
    "Dominik Livaković": {"Country": "Croatia", "Club": "Fenerbahçe", "Age": 31, "Position": "Goalkeeper"},
    "Vincent Aboubakar": {"Country": "Cameroon", "Club": "Hatayspor", "Age": 34, "Position": "Forward"},
    "Ciro Immobile": {"Country": "Italy", "Club": "Beşiktaş", "Age": 36, "Position": "Forward"},
    "Rafa Silva": {"Country": "Portugal", "Club": "Beşiktaş", "Age": 33, "Position": "Midfielder"},
    "Arthur Melo": {"Country": "Brazil", "Club": "Juventus", "Age": 29, "Position": "Midfielder"},
    "Teun Koopmeiners": {"Country": "Netherlands", "Club": "Juventus", "Age": 28, "Position": "Midfielder"},
    "Kenedy": {"Country": "Brazil", "Club": "Valladolid", "Age": 30, "Position": "Forward"},
    "Douglas Costa": {"Country": "Brazil", "Club": "Sydney FC", "Age": 35, "Position": "Forward"},
    "Dimitri Payet": {"Country": "France", "Club": "Vasco da Gama", "Age": 39, "Position": "Midfielder"},
    "James Rodríguez": {"Country": "Colombia", "Club": "Rayo Vallecano", "Age": 34, "Position": "Midfielder"},
    "Radamel Falcao": {"Country": "Colombia", "Club": "Millonarios", "Age": 40, "Position": "Forward"},
    "Arturo Vidal": {"Country": "Chile", "Club": "Colo-Colo", "Age": 39, "Position": "Midfielder"},
    "Alexis Sánchez": {"Country": "Chile", "Club": "Udinese", "Age": 37, "Position": "Forward"},
    "Keylor Navas": {"Country": "Costa Rica", "Club": "Free Agent", "Age": 39, "Position": "Goalkeeper"},
    "Guillermo Ochoa": {"Country": "Mexico", "Club": "AVS", "Age": 40, "Position": "Goalkeeper"},
    "Christian Pulisic": {"Country": "USA", "Club": "AC Milan", "Age": 27, "Position": "Forward"},
    "Weston McKennie": {"Country": "USA", "Club": "Juventus", "Age": 27, "Position": "Midfielder"},
    "Tyler Adams": {"Country": "USA", "Club": "Bournemouth", "Age": 27, "Position": "Midfielder"},
    "Gio Reyna": {"Country": "USA", "Club": "Borussia Dortmund", "Age": 23, "Position": "Midfielder"},
    "Alphonso Davies": {"Country": "Canada", "Club": "Bayern Munich", "Age": 25, "Position": "Defender"},
    "Jonathan David": {"Country": "Canada", "Club": "Lille", "Age": 26, "Position": "Forward"},
    "Tajon Buchanan": {"Country": "Canada", "Club": "Inter Milan", "Age": 27, "Position": "Defender"},
    "Leon Bailey": {"Country": "Jamaica", "Club": "Aston Villa", "Age": 28, "Position": "Forward"},
    "Michail Antonio": {"Country": "Jamaica", "Club": "West Ham United", "Age": 36, "Position": "Forward"},
    "Wataru Endo": {"Country": "Japan", "Club": "Liverpool", "Age": 33, "Position": "Midfielder"},
    "Kaoru Mitoma": {"Country": "Japan", "Club": "Brighton", "Age": 29, "Position": "Forward"},
    "Takefusa Kubo": {"Country": "Japan", "Club": "Real Sociedad", "Age": 25, "Position": "Forward"},
    "Takumi Minamino": {"Country": "Japan", "Club": "Monaco", "Age": 31, "Position": "Midfielder"},
    "Hwang Hee-chan": {"Country": "South Korea", "Club": "Wolves", "Age": 30, "Position": "Forward"},
    "Lee Kang-in": {"Country": "South Korea", "Club": "Paris Saint-Germain", "Age": 25, "Position": "Midfielder"},
    "Mehdi Taremi": {"Country": "Iran", "Club": "Inter Milan", "Age": 33, "Position": "Forward"},
    "Sardar Azmoun": {"Country": "Iran", "Club": "Shabab Al Ahli", "Age": 31, "Position": "Forward"}
}
